### ISSUE TITLE
Bottom Overflowed By number of Pixels

### ISSUE THREAD

**Issue by ahsansiddz1** [material-components/material-components-flutter-codelabs#268] opened 2022-02-04 20:15 UTC
When i am running this code in emulator (after changing the layout) its running smoothly,
but if am executing the same code and debugging into chrome it showing that error "Bottom Overflowed By number of Pixels"

I have added this line "resizeToAvoidBottomPadding: false"
but still facing the same issue.
![image](https://user-images.githubusercontent.com/79744131/152596912-608adbde-da36-4154-8cc0-aa8b43befe67.png)
![image](https://user-images.githubusercontent.com/79744131/152596964-c681860c-c70c-49fb-a36c-e738683cc0aa.png)

**Comment by guidezpl** [comment] 2022-04-21 07:11
Hi, I was unable to reproduce with the complete code on the `104-complete` branch so I'll close this for now. If you can provide reproduction steps and re-open the issue would be really helpful!

**Closed as completed by guidezpl** 2022-04-21 07:11 UTC
