### ISSUE TITLE
MDC-103: Tutorial needs to be updated to reflect fix for button color change

### ISSUE THREAD

**Issue by vitorpavanelli** [material-components/material-components-flutter-codelabs#139] opened 2018-12-13 10:07 UTC
Hi,

I might be wrong, but I think there is the need to update the code shown in the tutorial with the fix applied in the branch.

Please, can someone take a look at it?

Here are the changes I saw:
1) https://codelabs.developers.google.com/codelabs/mdc-103-flutter/#3
```
// TODO: Build a Shrine Theme (103)
final ThemeData _kShrineTheme = _buildShrineTheme();

ThemeData _buildShrineTheme() {
  final ThemeData base = ThemeData.light();
  return base.copyWith(
    accentColor: kShrineBrown900,
    primaryColor: kShrinePink100,
    buttonColor: kShrinePink100,
    scaffoldBackgroundColor: kShrineBackgroundWhite,
    cardColor: kShrineBackgroundWhite,
    textSelectionColor: kShrinePink100,
    errorColor: kShrineErrorRed,

   // Needs to be added
   buttonTheme: base.buttonTheme.copyWith(
      buttonColor: kShrinePink100,
    ),

   
  );
}
```

2) https://codelabs.developers.google.com/codelabs/mdc-103-flutter/#4

```
class AccentColorOverride extends StatelessWidget {
  const AccentColorOverride({Key key, this.color, this.child})
      : super(key: key);

  final Color color;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Theme(
      child: child,
      data: Theme.of(context).copyWith(
accentColor: color,
        brightness: Brightness.dark          //needs to be added
),
    );
  }
}
```

Thank you.

**Comment by willlarche** [comment] 2018-12-26 21:25
Thank you for reporting! This is a duplicate of #128 which has been resolved.

**Closed as completed by willlarche** 2018-12-26 21:25 UTC
Labels: duplicate
